#PROJECT SETTINGS
#no '' or "" on string objects!!!

[stft]
window_size = 256
fft_size = 256
hop_size = 160
window_type = hann

[sampling]
sr = 16000

[preprocessing]
# Input folders should be in root data folder
# Training
input_audio_folder_t = ../../data/Training/audio
input_annotation_folder_t =  ../../data/Training/Annotations

# Validation
input_audio_folder_v = ../../data/Validation/audio
input_annotation_folder_v =  ../../data/Validation/Annotations

# Output folders can be in speech folder for simplicity
# Training
output_predictors_matrix_t =  ../dataset/matrices/training_2A_S_predictors
output_target_matrix_t = ../dataset/matrices/training_2A_S_target

# Validation
output_predictors_matrix_v =  ../dataset/matrices/validation_2A_S_predictors
output_target_matrix_v = ../dataset/matrices/validation_2A_S_target

target_subject = all
target_story = all
sequence_length = 200
sequence_overlap = 0.5
target_delay = 0

[model]
load_model = ../models/bigru_PROVA2.keras
save_model = ../models/bigru_PROVA2.keras
last_latent_dim_dir = ../last_latent_dim

#matrix to be loaded for nn model training
training_predictors_load = ../dataset/matrices/training_2A_S_predictors.npy
training_target_load = ../dataset/matrices/training_2A_S_target.npy
validation_predictors_load = ../dataset/matrices/validation_2A_S_predictors.npy
validation_target_load = ../dataset/matrices/validation_2A_S_target.npy

#matrix to be loaded for nn model evaluation
reference_predictors_load = ../dataset/matrices/training_2A_S_predictors.npy
evaluation_predictors_load = ../dataset/matrices/validation_2A_S_predictors.npy
evaluation_target_load = ../dataset/matrices/validation_2A_S_target.npy

#Output folder for model predictions
modelOutputFolder = ../model_output
